ALTER TABLE inventory_entries
  ADD COLUMN IF NOT EXISTS iva_tipo TEXT NOT NULL DEFAULT 'gravado',
  ADD COLUMN IF NOT EXISTS costo_base NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS iva_valor NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS costo_total NUMERIC(14,2) NOT NULL DEFAULT 0;
